# Generated by Django 5.0.7 on 2024-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ingreso_count',
            field=models.IntegerField(default=1),
        ),
    ]
