# Generated by Django 5.0.7 on 2024-11-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_active_username',
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_active_email',
        ),
    ]
