# Generated by Django 5.0.7 on 2024-11-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
