# Generated by Django 5.0.7 on 2024-08-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('recommended_diet', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camas.cama')),
            ],
        ),
    ]
