# Generated by Django 5.0.7 on 2024-10-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camas', '0001_initial'),
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alergias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dietas.alergia')),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camas.cama')),
                ('recommended_diet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dietas.dieta')),
            ],
        ),
    ]
