# Generated by Django 5.0.7 on 2024-08-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
