# Generated by Django 5.0.2 on 2024-12-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='dietas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='dietas',
            field=models.ManyToManyField(related_name='pacientes', to='dietas.dieta'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='alergias',
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.ManyToManyField(related_name='pacientes', to='dietas.alergia'),
        ),
    ]
