# Generated by Django 5.0.7 on 2024-08-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoption',
            name='selected',
        ),
    ]
