# Generated by Django 5.0.7 on 2024-07-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('adicional_diario', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('firma', models.BooleanField(default=False)),
                ('algo_cereal', models.BooleanField(default=False)),
                ('algo_sandwich', models.BooleanField(default=False)),
                ('algo_tostada', models.BooleanField(default=False)),
                ('algo_barrita', models.BooleanField(default=False)),
                ('algo_cafe_leche', models.BooleanField(default=False)),
                ('algo_leche', models.BooleanField(default=False)),
                ('algo_jugo_agua', models.BooleanField(default=False)),
                ('algo_aromatica', models.BooleanField(default=False)),
                ('onces_cafe_galletas', models.BooleanField(default=False)),
                ('onces_batido', models.BooleanField(default=False)),
                ('onces_fruta', models.BooleanField(default=False)),
                ('onces_leche_entera', models.BooleanField(default=False)),
                ('onces_leche_deslactosada', models.BooleanField(default=False)),
                ('onces_azucar', models.BooleanField(default=False)),
                ('onces_endulzante', models.BooleanField(default=False)),
                ('desayuno_jugo_fruta', models.BooleanField(default=False)),
                ('desayuno_fruta', models.BooleanField(default=False)),
                ('desayuno_huevo_maicitos', models.BooleanField(default=False)),
                ('desayuno_huevo_revueltos', models.BooleanField(default=False)),
                ('desayuno_huevo_entero', models.BooleanField(default=False)),
                ('desayuno_queso_cuajada', models.BooleanField(default=False)),
                ('desayuno_arepa_blanca', models.BooleanField(default=False)),
                ('desayuno_pan', models.BooleanField(default=False)),
                ('desayuno_galletas', models.BooleanField(default=False)),
                ('desayuno_tostada', models.BooleanField(default=False)),
                ('desayuno_jugo_fruta_bebida', models.BooleanField(default=False)),
                ('desayuno_chocolate', models.BooleanField(default=False)),
                ('desayuno_cafe', models.BooleanField(default=False)),
                ('desayuno_aromatica_bebida', models.BooleanField(default=False)),
                ('desayuno_en_leche', models.BooleanField(default=False)),
                ('desayuno_en_agua', models.BooleanField(default=False)),
                ('almuerzo_consome', models.BooleanField(default=False)),
                ('almuerzo_sopa', models.BooleanField(default=False)),
                ('almuerzo_pechuga', models.BooleanField(default=False)),
                ('almuerzo_atun', models.BooleanField(default=False)),
                ('almuerzo_carne_res', models.BooleanField(default=False)),
                ('almuerzo_pescado', models.BooleanField(default=False)),
                ('almuerzo_papa', models.BooleanField(default=False)),
                ('almuerzo_platano', models.BooleanField(default=False)),
                ('almuerzo_arroz', models.BooleanField(default=False)),
                ('almuerzo_vegetales_crudos', models.BooleanField(default=False)),
                ('almuerzo_vegetales_calientes', models.BooleanField(default=False)),
                ('almuerzo_jugo_fruta', models.BooleanField(default=False)),
                ('almuerzo_leche', models.BooleanField(default=False)),
                ('almuerzo_aromatica', models.BooleanField(default=False)),
                ('almuerzo_golosina', models.BooleanField(default=False)),
                ('cena_consome', models.BooleanField(default=False)),
                ('cena_sopa', models.BooleanField(default=False)),
                ('cena_pechuga', models.BooleanField(default=False)),
                ('cena_atun', models.BooleanField(default=False)),
                ('cena_carne_res', models.BooleanField(default=False)),
                ('cena_pescado', models.BooleanField(default=False)),
                ('cena_papa', models.BooleanField(default=False)),
                ('cena_platano', models.BooleanField(default=False)),
                ('cena_arroz', models.BooleanField(default=False)),
                ('cena_vegetales_crudos', models.BooleanField(default=False)),
                ('cena_vegetales_calientes', models.BooleanField(default=False)),
                ('cena_agua_panela', models.BooleanField(default=False)),
                ('cena_jugo_fruta', models.BooleanField(default=False)),
                ('cena_leche', models.BooleanField(default=False)),
                ('cena_aromatica', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
