# Generated by Django 5.0.7 on 2024-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='adicionales',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
